'use client';

import { useState } from 'react';
import { CheckCircle2, ChevronDown, CreditCard, HelpCircle, MessageCircle, PackageSearch, ShieldCheck, WifiOff } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

const topics = [
  { id: 'sales', label: 'Checkout', icon: CheckCircle2, questions: [['How do I complete a sale?', 'Scan or search for each product, confirm quantities, choose cash or card, and complete the payment. The receipt can be printed after the sale.'], ['What if a card payment is declined?', 'Do not complete the sale. Ask the customer to try again or use another method, then only record the payment after the terminal shows approved.']] },
  { id: 'stock', label: 'Stock and reports', icon: PackageSearch, questions: [['How does the report group products?', 'It groups matching lines into groceries, beer, cider, wine, brandy and other products, while keeping each brand, size, and pack format as a separate line.'], ['How do I order low stock?', 'Edit the quantity beside each low-stock line and select the WhatsApp quote button. The message includes the exact size and quantity, so you can send it to your usual supplier or compare another supplier.']] },
  { id: 'payments', label: 'Card payments', icon: CreditCard, questions: [['Which card machine can I use?', 'Use the configured Yoco or iKhokha terminal, or another approved card machine configured by the shop owner. Complete the payment on the physical terminal first, then enter its approval reference in the POS.'], ['Does the POS charge the card?', 'The POS records the approved terminal result. It does not pretend to process a card when no payment terminal has approved it.']] },
  { id: 'offline', label: 'Connection', icon: WifiOff, questions: [['What happens when the internet drops?', 'The Electron terminal can save a completed sale locally and synchronize it when the connection returns. Keep the terminal open until the sync has completed.'], ['What should I do if sync does not return?', 'Check the network, keep the terminal online, and contact the shop administrator. Do not enter the same sale repeatedly while a queued sale is waiting.']] },
  { id: 'security', label: 'Security and access', icon: ShieldCheck, questions: [['Why is the terminal locked?', 'A lock can protect the shop when billing is overdue, the terminal lease has expired, the computer clock moved backwards, or the device is no longer registered. Correct the issue and contact the administrator.'], ['Why did I see terms before activation?', 'The first-run licence screen explains how the terminal, offline queue, cloud account, payment records, and security checks work. Acceptance is required before this computer can be activated.']] },
];

export default function HelpPage() {
  const [activeTopic, setActiveTopic] = useState('sales');
  const topic = topics.find((item) => item.id === activeTopic) || topics[0];
  const [openQuestion, setOpenQuestion] = useState(0);
  return <div className="mx-auto w-full max-w-5xl space-y-8"><div className="border-b pb-6"><p className="text-sm font-medium text-primary">Support desk</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Help and training</h1><p className="mt-2 max-w-2xl text-muted-foreground">Short answers for the moments that matter: serving a customer, checking stock, recording a card payment, or recovering from a connection problem.</p></div><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><Card className="h-fit"><CardHeader><CardTitle className="text-base">Topics</CardTitle></CardHeader><CardContent className="space-y-2">{topics.map(({ id, label, icon: Icon }) => <Button key={id} variant={activeTopic === id ? 'secondary' : 'ghost'} className="w-full justify-start" onClick={() => { setActiveTopic(id); setOpenQuestion(0); }}><Icon className="mr-2 h-4 w-4" />{label}</Button>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><HelpCircle className="h-5 w-5 text-primary" />{topic.label}</CardTitle><CardDescription>Keep this guide open while training a new cashier.</CardDescription></CardHeader><CardContent className="space-y-3">{topic.questions.map(([question, answer], index) => <div key={question} className="rounded-lg border"><button className="flex w-full items-center justify-between gap-4 p-4 text-left font-medium" onClick={() => setOpenQuestion(openQuestion === index ? -1 : index)}>{question}<ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${openQuestion === index ? 'rotate-180' : ''}`} /></button>{openQuestion === index && <p className="border-t px-4 py-4 text-sm leading-6 text-muted-foreground">{answer}</p>}</div>)}</CardContent></Card></div><div className="flex items-center gap-3 rounded-lg border bg-muted/30 p-4 text-sm text-muted-foreground"><MessageCircle className="h-5 w-5 shrink-0 text-primary" /><p>For activation, billing, a replacement terminal, or an unresolved transaction issue, contact the shop administrator with the time of the sale and the receipt reference.</p></div></div>;
}