import { CheckCircle2, Database, KeyRound, MonitorCheck, ShieldAlert, ShieldCheck } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

const controls = [
  { icon: KeyRound, title: 'Authentication and roles', text: 'Firebase Authentication identifies users. Server actions verify the token and restrict shop-owner, sales, and administrator operations.' },
  { icon: Database, title: 'Tenant isolation', text: 'Firestore rules and server-side shop checks prevent one shop from reading or changing another shop’s records.' },
  { icon: MonitorCheck, title: 'Terminal seats', text: 'Registered Electron terminals use activation tokens, hardware identity checks, device limits, reset controls, and short online leases.' },
  { icon: ShieldAlert, title: 'Offline and clock protection', text: 'Offline sales are queued for synchronization. The Electron shell checks lease expiry and detects a local clock moving backwards.' },
  { icon: ShieldCheck, title: 'Audit trail', text: 'Sales, billing changes, stock actions, terminal operations, and administrative events are recorded for review.' },
];

export default function SecurityPage() {
  return <div className="mx-auto w-full max-w-5xl space-y-8"><div className="border-b pb-6"><p className="text-sm font-medium text-primary">System controls</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Security and trust</h1><p className="mt-2 max-w-3xl text-muted-foreground">The POS is protected in layers. These controls reduce unauthorized access, cross-shop data exposure, payment mistakes, terminal cloning, and untracked changes.</p></div><div className="grid gap-4 md:grid-cols-2">{controls.map(({ icon: Icon, title, text }) => <Card key={title}><CardHeader><Icon className="h-5 w-5 text-primary" /><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{text}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" />Responsible security note</CardTitle><CardDescription>Security is risk reduction, not a promise that no attack is ever possible.</CardDescription></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">Keep Firebase rules deployed, protect server environment variables, use strong owner passwords, review the audit log, and keep Electron dependencies updated. Payment providers approve card transactions; the POS records the terminal reference and does not store card details.</p></CardContent></Card></div>;
}